server:
  port: 8081
  tomcat:
    max-http-form-post-size: -1

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  servlet:
    multipart:
      max-file-size: 15MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin
  # DB configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example?serverTimezone=Asia/Shanghai
    username: springuser
    password: ThePassword